### ISSUE TITLE
Keep the old readme example in examples/

### ISSUE THREAD

**Issue by Risto-Stevcev** [anuragsoni/routes#106]
It's not as obvious from the readme or the examples in the `examples/` folder that the routes are being partially applied and then the function invocation is completed in the `match'` result. You'd figure this out eventually by reading the code carefully and/or using the IDE to give you the type info.

It was a lot clearer in the [old example in the readme][1] how this works. I think the type info that was returned by mdx (simulating utop) was really helpful. My suggestion is to keep this older example in the `examples/` folder.

Why did the mdx get removed anyway?

[1]: https://github.com/anuragsoni/routes/tree/c9fb53ebb699b1f8dc429282eb082c97f579f86e#example

**Comment by anuragsoni** [comment]
I had removed the mdx initially because of having some issues with getting it to ignore running under some older ocaml versions. 

The reason to do that was because of the difference in how 'weak type variables are printed in the top level ('weak1 etc in 4.06 and above, vs '_a, '_b in older releases) this was causing the tests to fail for ocaml 4.05. But I suppose rather than give up on the mdx style readme, i should instead have improved the docs to talk about why the definition needs to be wrapped up in a thunk and refer to the value restriction (https://caml.inria.fr/pub/docs/manual-ocaml/polymorphism.html#ss:valuerestriction).

I should bring back the mdx style readme as I do like the literate program format where code can be mixed with some documentation explaining what's happening. I think it could be nice to showcase the following thins: 

* How a route can be constructed in pieces to avoid repeating the same prefix multiple times
* How to define a custom "pattern" that can be used for both printing and parsing
* Talk about what happens when multiple routes are defined but have patterns that can potentially overlap

I'll keep this issue open to track this work. Thanks again for bringing this up. This feedback is valuable to figure out what documentation content and format is proving beneficial.

**Comment by anuragsoni** [comment]
I've started some work at https://github.com/anuragsoni/routes/blob/start-bringing-back-mdx/README.md to add some examples in the readme that can be processed via mdx. If you have any suggestions for examples you'd like to see covered, feel free to add a comment here or make a PR against that branch.

Thanks,
Anurag
