### ISSUE TITLE
API for catch all route

### ISSUE THREAD

**Issue by sazarkin** [anuragsoni/routes#51]
Is it possible to add parser for `catch everything else`?
For example:
```ocaml
[`GET, search <$> s "search" *> everything]
let search s = print_string s;
```
allow to match to
```
GET /search/test          # print "test"
GET /search/test/1/test   # print "test/1/test"
```

**Comment by anuragsoni** [comment]
My first thought is to expose a `many` operation that can be used to consume `everything else`. 

Although i'd still have a slightly different behavior  from your example:

instead of `let search (s : string) = ...` it'd be `let search (s : string list) = ... `
That is a consequence of splitting a url path as the very first step of routing.

Will this behavior be acceptable for your needs?

**Comment by sazarkin** [comment]
yes, this will work

**Comment by anuragsoni** [comment]
I'll take some time to think about this. This needs to touch the untyped trie that is used for prefix matching and the typed applicative interface that does the final parsing. In the current trie approach i was using the fact that i could analyze the applicative parser to determine how many path params i'd need to match, to exit early in a few cases (see https://github.com/anuragsoni/routes/pull/54 for more details). I can remove that as i'm not sure if exiting early is actually going to be make a difference for a routing usecase.

But that being said, something else that i'd like to support is to convert a route to a user friendly string pattern, i.e. to_string (handler <$> s "foo" *> s "bar" *> int </> int) becomes ("foo/bar/:capture/:capture"). This can be useful for the user to print out all the route patterns they have in their application. This would understandably be challenging since we can't say how many parameters a "catch_all" pattern will end up matching.

**Comment by anuragsoni** [comment]
@sazarkin In an older version of routes i had explored supporting nested routes (example: https://github.com/anuragsoni/routes/blob/50a0e952db7cc431b523762be72611b1b630a59e/example/main.ml#L55) I need to figure our a nice way of supporting something like that again as that would help this usecase.

This can be done if we allow a route match to be marked as successful if all the path params match a given route but there are still some path params left to be compared. But i'd prefer then to also add a method that the user can run to check if their route definitions contain overlapping routes so they can take an appropriate action. basically some way to provide feedback if there are routes like `s "foo" *> capture_everything` and `s "foo" *> int </> ...`

**Comment by Lupus** [comment]
@anuragsoni have you had any ideas on how this can be moved forward? We're thinking of creating API gateway that should scan service discovery state, get service names, some tags, and build routing of requests. But we won't have exact matches, only prefixes. I.e. `api.example.com/service-name/v1/some/path/to/handler`, so given `service-name` and some `/v1` prefix derived from tags, we'd like to match `/service-name/v1/%whatever%` and proxy-pass `/v1/%whatever%` to instance of service. Do you think such use case could fit `routes`? Or it deserves some specialized prefix-matching thing?

**Comment by anuragsoni** [comment]
@Lupus I haven't been able to come up with a good api for this at the moment. I think its a very valid usecase and i'd like to get this supported. Adding support for a wildcard that just returns a `string` or a `string list` is probably easier than what i think. Supporting prefix searches on the backing trie shouldn't be too hard. The printing via sprintf might be a little awkward but i guess that can also be easier if we end up limiting this to a `string` or a `string list`.

**Comment by Lupus** [comment]
Just matching everything and returning it as a `string` sounds good to me. May be `string list` would be even too opinionated for such cases? If user declares that they want to get everything after `/v1/foo/` and handle themselves, probably they are motivated enough to process it as they see fit (in case of api gateway, that does not even need to be processed).

**Comment by anuragsoni** [comment]
This was tackled by #118
